### ISSUE TITLE
Allow code to compile without Exodus-II

### ISSUE THREAD

**Issue by bishtgautam** [TDycores-Project/TDycore#125]
add `#if defined (PETSC_HAVE_EXODUSII)` around the exodus code.

**Comment by jedbrown** [comment]
What other mesh formats are we interested in? PETSc can read Gmsh without any plugins, and if we're on prisms now, triangular (map plane) meshes that conform to ridge lines should be quite feasible with Gmsh. The main appeal of Exodus seems to be export from Cubit, but I don't know how much our workflows will need that. A workflow without Exodus is a lot simpler to build for and easier to make reproducible tutorials than anyone can follow (without needing to get a Cubit/Trelis license).

**Comment by bishtgautam** [comment]
IMO PETSc's support of HDF5 will be the default format because HDF5 will provide a scalable I/O. I'm not familiar with Gmsh to have an opinion if we should support it. If we do decide on supporting Gmsh format, I would say it is a feature that is nice to have, but not critical.

**Comment by nocollier** [comment]
I am fine to drop Exodus. I did it initially only because it was the most
convenient way (at the time) to load a mesh. Or perhaps that is the method
I found an example for and so I adopted it. That there are now better
scaling formats supported means it is time to move on.

I feel Jed's point about supporting Gmesh is more about convenience if we
were to give tutorials in the future. It would make configure time of PETSc
much faster and could be attractive for testing. We are talking about an
additional TDy constructor to support the format, correct?

**Comment by jedbrown** [comment]
`DMPlexCreateFromFile()` works with any format so it shouldn't need any special code in TDycore. It's just a matter of the workflow we demo in tutorials. We can't start with preprocessed HDF5 format because nobody has that on hand for _their_ watershed.

**Comment by bishtgautam** [comment]
>We are talking about an additional TDy constructor to support the format, correct?

The issue with I/O format has more to do with outputting the data rather than reading in the mesh. The TDycore needs to write out various data fields such as pressure, saturation, etc. @leorosie added code in the TDycore to output various data fields data in ExodusII format by leveraging PETSc's functionality. Now, @leorosie is working on adding the ability to output various TDycore's data fields in HDF5-XDMF, along with the `*.xmf`.

Regarding future demos, users can bring in their watershed data in any format that is supported by `DMPlexCreateFromFile` (as Jed pointed out), but TDycore will presently only output in `.exo` or `.h5` format.
