### ISSUE TITLE
Ensure that ghost cells exist for nodes in MPFA-O

### ISSUE THREAD

**Issue by bishtgautam** [TDycores-Project/TDycore#135]
@jeff-cohere I think one solution could be to save information about "additional" cells that are shared by a vertex but are not within local+ghost cells that a graph partitioner will provide information about. To do so, the following two functions need to be updated:
- [SaveMeshGeometricAttributes](https://github.com/TDycores-Project/TDycore/blob/master/src/mesh/tdycoremesh.c#L380)
- [SaveMeshConnectivityInfo](https://github.com/TDycores-Project/TDycore/blob/master/src/mesh/tdycoremesh.c#L541)

In order to save information about additional cells, memory needs to be correctly allocated in [TDyAllocateMemoryForMesh](https://github.com/TDycores-Project/TDycore/blob/master/src/mesh/tdycoremesh.c#L300). Memory allocation for the mesh and saving attributes about the mesh are implemented at [tdympfao.c#L310](https://github.com/TDycores-Project/TDycore/blob/master/src/mpfao/tdympfao.c#L310) and [tdympfao.c#L407](https://github.com/TDycores-Project/TDycore/blob/master/src/mpfao/tdympfao.c#L407), respectively.

What do you think?

**Comment by jeff-cohere** [comment]
I think as long as these functions are called by every process at the same time, this is a relatively simple approach that could work very well. I'll take a look.

**Comment by jeff-cohere** [comment]
From the mailing list:

-----

If c0 is owned by MPI rank 0 and all other cells are owned by different MPI ranks, is there a stencil type that will lead to c1-c5 being ghost cells on rank 0? Essentially, I need information about all cells sharing a vertex on rank 0.

A Plex is a parallel collection of local meshes. Each local mesh is guaranteed to contain the closure (transitive closure of cone) of each point. However, the local mesh is _not_ guaranteed to contain the supports of points.

Thus, if you need cell neighbors you will need to DMPlexDistribute() with an overlap argument of 1. Then all those cells will be in the local mesh. You can distinguish an "owned" cell from a "ghost" cell by searching for it in the pointSF (DMGetPointSF). I do this using PetscSFGetGraph() and searching in the leaves, which are sorted, so you can use PetscFindInt().

**Comment by jeff-cohere** [comment]
Hey @bishtgautam , do we have a test in mind that relies on nodal control volumes being correct for a parallel run? Is there an existing serial MPFA-O test that doesn't yet work in parallel that would benefit from having the nodal ghost cells available?

**Comment by bishtgautam** [comment]
Hi @jeff-cohere I don't have a test to reproduce the error. I was attempting to coming up with a PETSc DMPlex example to highlight the issue but was unsuccessful. I believe the easiest approach to debug this would be via PETSc DMPlex example (outside TDycore).

**Comment by knepley** [comment]
If you tell me what you want, I will write it. So maybe draw me a simple picture.

**Comment by jeff-cohere** [comment]
> If you tell me what you want, I will write it. So maybe draw me a simple picture.

I'm extrapolating a bit from what Gautam has said above, so please correct me (both of you) if this doesn't make sense. 

The multi-point flux approximation defines nodal control volumes by gathering the subcells attached to the node in question. From what I understand, our MPFA-O implementation currently associates with a node only those subcells that belong to locally-owned cells on a domain. This means that nodes on parallel domain boundaries have volumes that are too small. Gautam, is that correct?

If this is the case, I'd expect to be able to craft a parallel test problem to check that the nodal volumes are correct. I haven't poked around very much, so I don't know for sure, but it doesn't seem like we have low-level "unit tests" that check these sorts of things. Such a parallel test would certainly fail for any node that didn't have all of its adjoining subcells associated with it. I think we should construct such a test to demonstrate that our MPFA-O method has this flaw.

Matt: I think I understand the snippet I pasted here from the mailing list, but it would be even nicer to see an example of how such nodal volumes can be constructed with DMPlex and its star forests/cones/etc. Even if you define a nodal volume as the aggregated cells attached to a node instead of subcells, that would give me all the information I needed to associate the subcells.

Hopefully this makes some sort of sense!

**Comment by knepley** [comment]
Sure. let's do topology first. To get the cells around a vertex, you could just call

  DMPlexGetTransitiveClosure(dm, vertex, PETSC_FALSE, ...)

and then iterate over those points. However, there is a slightly higher level if you want
it, using

  DMSetBasicAdjacency(dm, PETSC_TRUE, PETSC_TRUE)

and then

  DMPlexGetAdjacency(...)

which is exactly what DMPlexDistributeOverlap() uses to get the overlap. So if this is
setup correctly,  then you can just pass overlap = 1 to DMPlexDistribute() and you will
get the cells needed for MPAO.

**Comment by bishtgautam** [comment]
To resolve this issue, is the idea to add custom code in TDycore or add code in PETSc or correctly use PETSc's code?

**Comment by knepley** [comment]
I believe we just have to use things correctly

**Comment by jeff-cohere** [comment]
I think the fact that parallel simulations are working (+/- current issues) makes this task unnecessary.
