### ISSUE TITLE
Add documentation for the library

### ISSUE THREAD

**Issue by bishtgautam** [TDycores-Project/TDycore#24]

**Comment by bishtgautam** [comment]
@jeff-cohere commentted regarding documentation on [PR-100](https://github.com/TDycores-Project/TDycore/pull/100#issuecomment-719025564) and I'm moving that discussion here.

@jeff-cohere, I think adding documentation would be useful, but I don't have experience enough to advocate for one or the other approach.

- PETSc has its own very sophisticated system of creating the doc from the comments on the code. Not sure if we should try to use that framework.
- I checked [libCEED](https://github.com/CEED/libCEED) and it has user+dev guide within `src/doc`, which is hosted on [readthedocs](https://libceed.readthedocs.io/en/latest/). Could not figure out if doxygen is being used by libCEED. (cc: @jedbrown). 

Do others have suggestions/experience regarding how should we go about creating documentation for the library?

**Comment by jeff-cohere** [comment]
Doxygen is a decent out-of-the-box approach. It was written primarily for use with C++, but I know some tricks to get it to work well with C. If PETSc's approach can be applied to TDycore, that'd be another good option.

**Comment by nocollier** [comment]
It appears that libCEED does use Doxygen at least to generate some
intermediate xml.

https://github.com/CEED/libCEED/blob/main/doc/README.md

When I think about documentation that I use vs that I don't, I am usually
googling things. I look a lot at python docs like
numpy/scipy/netCDF/xarray/pandas but more often than not I get there via a
google search. So I would advocate whatever we choose being online so it
gets indexed.

I also spend a lot of time looking around at the PETSc docs which I tend to
access directly via their website because I don't know what function I
should call. I love that they have a lot of their API on one page that I
can just CTRL-F to find functions that might work for me. For example, I
used CTRL-F "PetscSpaceSet" yesterday to figure out how I should create a
space for a test I was running. However, I also use the PETSc documentation
a lot with "highlight function" + "ESC" + "." inside emacs (uses etags).
This takes me right to the source code and I can read the docs inline.

Nate

**Comment by jedbrown** [comment]
Yep, libCEED uses Doxygen-style comments and a Sphinx plugin called Breathe to create its [API pages](https://libceed.readthedocs.io/en/latest/api/CeedBasis/). Some editors (e.g., VS Code) have smart rendering for such comments. I would _not_ recommend using Sowing (the man page tooling used by PETSc and MPICH) in new projects.

I would recommend using Clangd and/or GNU Global for indexing/code navigation. https://docs.petsc.org/en/latest/manual/other/?highlight=clangd#emacs-users
etags is stone-age by comparison.

**Comment by jeff-cohere** [comment]
If we agree that Doxygen-style markup is the way to go, I can get started setting this up. Getting the annotations into the code is the time-consuming part. Breathe/Sphinx sounds good to me--it's much nicer looking than what Doxygen produces out of the box. But I think any API reference that's available online is better than nothing.

**Comment by jedbrown** [comment]
That sounds good to me. I think the setup in libCEED works pretty well and could largely be copied over. Feel free to ping if you have questions.

**Comment by jeff-cohere** [comment]
Now that the Doxygen target and the website stuff is in place, I suppose we just need to add some examples of Doxygen markup for people to follow in documenting their types and functions. Anything else for this issue? (I'm opening a separate one for the style guide).

**Comment by jeff-cohere** [comment]
I think we've pushed this far enough along that remaining work can be outlined in more specific issues.
